### PR TITLE
feat: cargo fmt and actions to force format

### PR DESCRIPTION
**Pull request by AveryQi115**
- cargo fmt current code
- actions CI include: format check, clippy check, cargo test

### CODE REVIEW

**Comment by skyzh** [comment]
i would not recommend auto-fix fmt. just use `cargo fmt --check` would be good enough :)

**Comment by skyzh** [comment]
like in this case, it seems that you cannot retrieve the token...?

**Comment by AveryQi115** [comment]
> like in this case, it seems that you cannot retrieve the token...?

I think it is related to nightly dependencies issue?

**Comment by skyzh** [comment]
i think the action you are using in rustfmt/format needs a GitHub token to add commits to the pull request.

actually i have an action file that are used across almost all my Rust projects: https://github.com/skyzh/type-exercise-in-rust/blob/main/.github/workflows/ci.yml

**Comment by skyzh** [comment]
and you can pin https://github.com/cmu-db/optd/blob/main/rust-toolchain to a specific version (1.75 is the latest one?) so that there're no more fmt issues

**Pull request closed without merging**
